### PR TITLE
fix: avoid codegen when configuration changes

### LINKED ISSUE #82: Codegen: false does not prevent codegen on config change
When codegen is set to false, we prevent the codegen output on the initial build, but the codegen will still happen if the panda.config file changes.

To reproduce In the playground app (or most panda projects):
1. add `codeGen: false` to the pandabox vite plugin config
2. While Vite is running, in your panda config change the outdir to some incorrect value
3. The new outdir will be output

### PR DESCRIPTION
**Pull request by literalpie**
Fixes #82

### CODE REVIEW

File: packages/unplugin/src/plugin/core.ts [hunk 1]
```diff
@@ -68,8 +68,15 @@ export interface PandaPluginOptions extends Partial<PandaPluginHooks>, Pick<Tran
...
    * @default true
+   * @deprecated Use 'codegen' instead
    */
   codeGen?: boolean
+  /**
+   * Generate a styled-system folder on server start.
+   *
+   * @default true
+   */
+  codegen?: boolean
```
Comment (literalpie) [inline packages/unplugin/src/plugin/core.ts:79]: I also renamed this to have casing consistent with most places "codegen" is used by Panda. Deprecating might be overkill since this option was just added, but I was thinking it's nice to deprecate it at least for a bit since it's not hard.

File: packages/unplugin/src/plugin/create-context.ts [hunk 2]
```diff
@@ -61,7 +62,9 @@ export const createContext = (options: ContextOptions) => {
 
       // logger.info('ctx:updated', 'config rebuilt ✅')
       await panda.hooks['config:change']?.({ config: panda.config, changes: affecteds })
-      await codegen(panda, Array.from(affecteds.artifacts))
+      if(options.codegen) {
+        await codegen(panda, Array.from(affecteds.artifacts))
```
Comment (literalpie) [inline packages/unplugin/src/plugin/create-context.ts:66]: This is the key change

**Review by astahmer — APPROVED** [review]
